---
title: "SRT411A0.Rmd"
author: "Jannat Bhalla"
date: "February 17, 2018"

# github user: "jbhalla04"
# assignment: "The purpose of this assignment is to complete basic R exercises and upload their code and the results to github. The document used for this assignment is: https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf".
# sources used: "https://www.statmethods.net/advgraphs/parameters.html, https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf""

output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r}
# ToDo 1
(2016 - 2014) / (2014 - 1997) * 100
```
```{r}
# ToDo 2
todo <- (2016 - 2014) / (2014 - 1997) * 100
```

```{r}
# ToDo 3
b=c(4,5,8,11)
sum(b)
```

```{r}
# ToDo 4
x= rnorm(100)
plot(x)
```

```{r}
# ToDo 5
help(sqrt)
```

```{r}
# ToDo 6
# firstscript.R 
 source("firstscript.R")
```

```{r}
# ToDo 7
Q=matrix(data=(P = seq(from=31, to=60, by=1)), ncol=5, nrow=6)
Q
```

```{r}
# ToDo 8
x1= rnorm(100)

x2= rnorm(100)

x3= rnorm(100)

t= data.frame(a=x1, b=x1+x2, c=x1+x2+x3)
plot(t)
```

```{r}
# ToDo 9
# lwd:line width relative to the default 
# (default=1). 2 is twice as wide.

# pch: option to specify symbols to use 
# when plotting points.

# cex: number indicating the amount by 
# which plotting text and symbols should 
# be scaled relative to the default.

x1= rnorm(100)

x2= rnorm(100)

x3= rnorm(100)

t= data.frame(a=x1, b=x1+x2, c=x1+x2+x3)
plot(t)
plot(t$a, type="l", ylim=range(t),
     lwd=3, col=rgb(1,0,0,0.3))
lines(t$b, type="s", lwd=2,
      col=rgb(0.3,0.4,0.3,0.9))
points(t$c, pch=20, cex=4,
       col=rgb(0,0,1,0.3))
```

```{r}
# ToDo 10
d = data.frame(g = c(3,4,5),h = c(12,43,54))
write.table(d, file="tst1.txt", row.names=FALSE)
d2 = read.table(file="tst1.txt",header=TRUE)
d2$g*5
```

```{r}
# ToDo 11
x= rnorm(100)
mean(sqrt(x))
```

```{r}
# ToDo 12
#Make a graph with on the x-axis: today, Sinterklaas
#2014 and your next birthday and on
#the y-axis the number of presents you expect on
#each of these days. Tip: make two vectors first.
date2=strptime(c("20170217000000", "20141225000001", "20181204000000"), format = "%Y%m%d%H%M%S")
x=date2
y=c(2,6,4)
plot(x,y)
```

```{r}
# ToDo 13
fun= function(arg1,arg2 )
{
  vector[i]=arg1[i];
  for(i in length(vector))
  {
    
  }
}
```